distributionDetailsFile: "./Inputs/*.xlsx" # Path of the file contaning the distribution details 
undallocatedBundlesFolder: "./Inputs/Grabbed_Results" 
generatedDistributionsSaveFolder: "./Outputs/Generated_Distributions" # Folder to save the generated distribution
mergedOutputFolderPath: "./Outputs/merged_outputs"
campList: [] # Eg: ["Thiruvananthapuram", "Kollam", "Pathanamthitta",  "Alappuzha"]
qpSeries: ""  # P,Q,R,S..
examName: ""  # S1 PG May 2023