distributionDetailsFile: "./Inputs/Distribution/" # Path of the file containing the distribution details
undallocatedBundlesFolder: "./Inputs/Grabbed_Results/"
generatedDistributionsSaveFolder: "./Outputs/Generated_Distributions/" # Folder to save the generated distribution
mergedOutputFolderPath: "./Outputs/merged_outputs/"
campList: ["Thiruvananthapuram", "Kollam", "Pathanamthitta", "Alappuzha"] # Eg: ["Thiruvananthapuram", "Kollam", "Pathanamthitta",  "Alappuzha"]
qpSeries: "" # P,Q,R,S..
qpStartRange: "" # 5645
qpEndRange: "" # 5670
examName: "" # S1 PG May 2023

nopecha: "bqmxcoa79g3d0z6w" # nopecha api key

# examerp slcm site user credentials for auto login
username: "5483"
password: "Cdunit#ek2"
# Note that the distributionDetailsFile name must be in this format,
# for example, 'S3 PG Feb 2023_distribution.xlsx,' where 'S3 PG Feb 2023' is the same as the value given to examName.
